name: mokasem workflow
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore -c Release

      - name: Run unit tests
        run: dotnet test redisPlayground.Tests/redisPlayground.Tests.csproj --no-build -c Release --verbosity normal

  frist_job:
    runs-on: ubuntu-latest
    steps:
      - name: printmyname
        run: echo "as salam alykum."
      - name: printmyname
        run: |
           echo "as salam alykum. number two######"
           echo "as salam alykum. number two@@@@@@@@@@"
